# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9faf7f119afefed2e2e052e1b497cc83b24997230849adb0dedeb712960e8c0e427e15a2fc1afc8ff639fb62e5400a75774c81b990823ea5446856c1ceed355a

test:
  secret_key_base: 99092bceb70882335b5e461ec10b557cb3c54107e88504c582965d61d7b9a1547068fc81670d3b2361996951940c848881627bb969a2129ec08267b9da3894f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
